const config=require('./demand-config.cjs');
const tr=(th,en)=>`<span data-en="${en}">${th}</span>`;
const choices=(name,items,type='radio')=>`<div class="choices">${items.map(([value,th,en])=>`<label class="choice${name==='requested_size'&&value==='unsure'?' buddy-choice':''}"><input type="${type}" name="${name}" value="${value}">${tr(th,en)}</label>`).join('')}</div>`;
const question=(n,th,en,body)=>`<fieldset class="question"><legend><span class="question-number">${n}</span>${tr(th,en)}</legend>${body}</fieldset>`;
function renderRegistrationPage(home){
 const credentials=home.match(/const SUPABASE_(?:URL|ANON_KEY)\s*=\s*"[^"]*";/g).join('\n');
 const persistence=home.slice(home.indexOf('const CONFIGURED'),home.indexOf('const buddyAccessKey'));
 const privacy=home.match(/<dialog id="privacyDialog"[\s\S]*?<\/dialog>/)[0];
 const uses=choices('use_case',[['personal','ของใช้ส่วนตัว','Personal belongings'],['moving','ย้ายบ้าน','Moving home'],['renovation','รีโนเวทบ้าน','Renovation'],['documents','เอกสาร','Documents'],['stock','สต็อกสินค้า','Stock / inventory'],['equipment','อุปกรณ์ธุรกิจ','Business equipment'],['furniture','เฟอร์นิเจอร์','Furniture'],['other','อื่น ๆ','Other']],'checkbox');
 const sizes=choices('requested_size',[['1_2','1–2 ตร.ม.','1–2 m²'],['3_4','3–4 ตร.ม.','3–4 m²'],['5_6','5–6 ตร.ม.','5–6 m²'],['7_10','7–10 ตร.ม.','7–10 m²'],['over_10','มากกว่า 10 ตร.ม.','Over 10 m²'],['unsure','ยังไม่แน่ใจ ให้ Buddy ช่วยประเมิน','Not sure — let Buddy help']]);
 const timing=choices('desired_move_in',[['now','พร้อมใช้ทันที','As soon as possible'],['within_7_days','ภายใน 7 วัน','Within 7 days'],['within_30_days','ภายใน 30 วัน','Within 30 days'],['in_1_3_months','1–3 เดือน','In 1–3 months'],['over_3_months','มากกว่า 3 เดือน','Over 3 months'],['unsure','ยังไม่แน่ใจ','Not sure yet']]);
 const duration=choices('expected_duration',[['1_3_months','1–3 เดือน','1–3 months'],['3_6_months','3–6 เดือน','3–6 months'],['6_12_months','6–12 เดือน','6–12 months'],['over_1_year','มากกว่า 1 ปี','Over 1 year'],['unsure','ยังไม่แน่ใจ','Not sure yet']]);
 const readiness=choices('readiness_level',[['ready_to_confirm','พร้อมยืนยันทันที','Ready to confirm'],['wants_visit','ขอเข้าดูสถานที่ก่อน','I would like to visit first'],['needs_details','ขอคุยรายละเอียดเพิ่มเติม','I would like to discuss the details'],['researching','ยังเก็บข้อมูลเปรียบเทียบอยู่','Still comparing options']]);
 const priceResponses=choices('price_response',[['accept_ready','โอเค ถ้ามีห้องพร้อมสามารถตัดสินใจได้','Works for me — I could decide if a room is available'],['accept_visit','โอเค แต่อยากเข้าดูสถานที่ก่อน','Works for me — I would like to visit first'],['too_high','สูงกว่าที่คิด','Higher than expected'],['comparing','ยังเปรียบเทียบราคาอยู่','Still comparing prices']]);
 return `<!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>ให้ Buddy เช็กห้องและราคาให้ | StorageBuddy</title><meta name="description" content="บอกของที่ต้องการเก็บ ขนาด และวันที่ต้องการใช้ ให้ Buddy ช่วยเช็กตัวเลือกที่เหมาะกับคุณ ไม่มีการชำระเงินในขั้นตอนนี้"><link rel="canonical" href="https://storagebuddyth.com/register/"><meta property="og:title" content="ให้ Buddy เช็กห้องและราคาให้"><meta property="og:description" content="บอกความต้องการใน 3 ขั้นตอนสั้น ๆ ให้บัดดี้ช่วยดูแล"><meta property="og:url" content="https://storagebuddyth.com/register/"><meta property="og:image" content="https://storagebuddyth.com/assets/buddy_banner_th.webp"><meta name="theme-color" content="#087f5b"><link rel="icon" href="/assets/storagebuddy_logo_20260912.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Thai:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/demand-form.css?v=4"></head><body>
<header class="form-header"><a href="/" aria-label="StorageBuddy home"><img src="/assets/storagebuddy_logo_20260912.png" alt="StorageBuddy" width="76" height="76"></a><div><a href="/" data-en="Visit website">ดูเว็บไซต์</a><button id="langBtn" type="button" aria-label="Switch to English">🌐 EN</button></div></header>
<main class="form-main"><div class="form-intro"><p class="eyebrow">STORAGEBUDDY RAMA 3</p><h1 data-en="Let Buddy find the right space for you">ให้ Buddy เช็กห้องและราคาให้</h1><p data-en="A few details help us find a size and timing that work for you.">บอกความต้องการนิดเดียว ให้บัดดี้ช่วยเลือกขนาดและช่วงเวลาที่เหมาะกับคุณ</p><div class="trust-note" data-en="No payment or deposit at this stage. You decide after the room, price and date are confirmed.">ไม่มีการชำระเงินหรือค่ามัดจำในขั้นตอนนี้ คุณตัดสินใจเมื่อยืนยันห้อง ราคา และวันใช้งานแล้ว</div></div>
<nav class="form-progress" aria-label="Questionnaire progress"><span data-step-indicator="0" aria-current="step">1 ${tr('ของและพื้นที่','Items & space')}</span><span data-step-indicator="1">2 ${tr('เวลาและราคา','Timing & price')}</span><span data-step-indicator="2">3 ${tr('ให้ Buddy ติดต่อ','Contact')}</span></nav>
<form id="demandForm" novalidate><section class="form-step" data-step="0">
${question(1,'คุณต้องการเก็บอะไร?','What would you like to store?',`<p class="hint" data-en="Choose all that apply.">เลือกได้มากกว่าหนึ่งข้อ</p>${uses}<label class="text-field" for="itemDescription">${tr('มีของอะไรบ้าง? (ไม่บังคับ)','Any item details? (optional)')}<textarea id="itemDescription" maxlength="1800" rows="2" placeholder="เช่น กล่อง 10 ใบ โซฟา 1 ตัว" data-en-placeholder="e.g. 10 boxes and a sofa"></textarea></label>`)}
${question(2,'ต้องการพื้นที่ประมาณเท่าไหร่?','How much space might you need?',sizes+`<details id="sizeAssistant" class="optional size-assistant"><summary data-en="Let Buddy estimate my size">ให้ Buddy ช่วยประเมินขนาด</summary><p class="hint" data-en="Use the item details above, or add up to 4 photos (JPG, PNG or WebP; 8 MB each).">ใช้รายละเอียดของด้านบน หรือเพิ่มรูปได้สูงสุด 4 รูป (JPG, PNG หรือ WebP รูปละไม่เกิน 8 MB)</p><label class="text-field" for="estimatePhotos">${tr("เพิ่มรูปของ (ไม่บังคับ)","Add item photos (optional)")}<input id="estimatePhotos" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><div id="estimatePreviews" class="estimate-previews"></div><p class="hint" data-en="Press Estimate to let Buddy check your items. Photos are not saved with your enquiry.">กดประเมินเพื่อให้ Buddy ช่วยดูของและแนะนำขนาด รูปจะไม่ถูกบันทึกพร้อมคำขอของคุณ</p><button id="estimateSize" class="secondary" type="button" data-en="Estimate my size">ช่วยประเมินขนาดให้ฉัน</button><p id="estimateMessage" role="status"></p><div id="estimateResult" hidden><strong id="estimateRange"></strong><p id="estimateReason"></p><p class="hint" data-en="An initial estimate. Buddy will confirm the space needed with you.">เป็นขนาดประเมินเบื้องต้น Buddy จะช่วยยืนยันพื้นที่ที่เหมาะสมกับคุณอีกครั้ง</p><button id="acceptEstimate" class="secondary" type="button" data-en="Use this recommendation">ใช้ขนาดที่แนะนำ</button></div></details><p class="hint" data-en="Not knowing your size is fine. Buddy can help estimate it.">ไม่ต้องรู้ขนาดแน่นอนก็ได้ Buddy ช่วยประเมินให้คุณได้</p>`)}
</section><section class="form-step" data-step="1" hidden>
${question(3,'ต้องการเริ่มใช้เมื่อไหร่?','When would you like to start?',timing+`<details class="optional"><summary data-en="Have an exact date? (optional)">มีวันที่ในใจแล้ว? (ไม่บังคับ)</summary><label class="text-field" for="desiredDate">${tr('วันที่ต้องการเริ่มใช้','Preferred start date')}<input id="desiredDate" type="date"></label></details>`)}
${question(4,'คาดว่าจะเช่านานประมาณเท่าไหร่?','How long do you expect to rent?',duration)}
${question(5,'ราคาแบบไหนที่เหมาะกับคุณ?','What price would work for you?',`<div id="targetQuote" hidden><p id="quoteText" class="quote"></p><p class="hint" data-en="Target price for first customers. Final price confirmed before contract.">ราคาเป้าหมายสำหรับลูกค้ารอบแรก ราคาสุดท้ายยืนยันก่อนทำสัญญา</p><h3 data-en="How does this price work for you?">ราคานี้เป็นอย่างไรสำหรับคุณ?</h3>${priceResponses}</div><div id="budgetOnly"><p class="hint" data-en="Buddy will check pricing for your size. You can leave your budget blank.">Buddy จะเช็กราคาสำหรับขนาดที่คุณต้องการให้ ไม่จำเป็นต้องระบุงบประมาณก็ได้</p></div><label class="text-field" for="budget">${tr('งบประมาณต่อเดือนที่คิดว่าเหมาะสม (ไม่บังคับ)','Your monthly budget (optional)')}<div class="money-input"><input id="budget" type="number" min="1" max="1000000" step="1" inputmode="numeric" placeholder="บาท / เดือน" data-en-placeholder="THB / month"><span>THB</span></div></label>`)}
</section><section class="form-step" data-step="2" hidden>
${question(6,'ถ้ามีห้องตรงกับขนาด ราคา และวันที่ต้องการ คุณพร้อมแค่ไหน?','If the size, price and date fit, how ready are you?',readiness)}
${question(7,'ให้ Buddy ติดต่อกลับทางไหนสะดวกที่สุด?','How should Buddy contact you?',choices('contact_preference',[['line','LINE','LINE'],['phone','โทรศัพท์','Phone'],['messenger','Messenger','Messenger']])+`<div class="contact-fields"><label class="text-field" for="customerName">${tr('ชื่อ *','Name *')}<input id="customerName" autocomplete="name" required minlength="2" maxlength="120"></label><label class="text-field" for="phone">${tr('โทรศัพท์ *','Phone *')}<input id="phone" type="tel" inputmode="tel" autocomplete="tel" required maxlength="24"></label><label class="text-field" id="lineField" for="lineId" hidden>${tr('LINE ID (ถ้ามี)','LINE ID (if you have one)')}<input id="lineId" maxlength="100" autocomplete="off"><span class="hint" data-en="Or add our LINE after sending this form.">หรือเพิ่ม LINE ของบัดดี้หลังส่งแบบฟอร์มได้เลย</span></label><p id="messengerHint" class="hint" hidden data-en="After sending, message our Facebook page so we can find your conversation.">หลังส่งแบบฟอร์ม ทักเพจ Facebook เพื่อให้บัดดี้ค้นหาแชทของคุณได้</p></div><details class="optional"><summary data-en="Add email (optional)">เพิ่มอีเมล (ไม่บังคับ)</summary><label class="text-field" for="email">${tr('อีเมล','Email')}<input id="email" type="email" autocomplete="email" maxlength="254"></label></details>`)}
<label class="consent"><input id="consent" type="checkbox" required><span>${tr('ยินยอมให้ StorageBuddy โดยบริษัท โฟลว์คราฟท์ โพรเซส โซลูชั่น จำกัด บันทึกข้อมูลและติดต่อเกี่ยวกับความต้องการพื้นที่เก็บของของฉัน','I agree that StorageBuddy, operated by FLOWCRAFT PROCESS SOLUTION CO.,LTD., may save my details and contact me about my storage needs.')} <button type="button" data-privacy data-en="Privacy">ความเป็นส่วนตัว</button></span></label>
</section><div class="honeypot" aria-hidden="true"><label>Website<input id="website" tabindex="-1" autocomplete="off"></label></div><p id="formMessage" class="form-message" role="alert" tabindex="-1"></p><div class="form-actions"><button id="backBtn" class="secondary" type="button" hidden data-en="Back">ย้อนกลับ</button><button id="nextBtn" class="primary" type="button" data-en="Continue →">ถัดไป →</button><button id="submitBtn" class="primary" type="submit" hidden data-en="Let Buddy check rooms and prices for me">ให้ Buddy เช็กห้องและราคาให้</button></div><p class="small-note" data-en="Your request does not reserve a room. No money is collected.">การส่งข้อมูลยังไม่ใช่การจองห้อง และไม่มีการเรียกเก็บเงิน</p></form>
<section id="leadSuccess" class="success" hidden tabindex="-1"><div class="success-heart">💚</div><h2 data-en="We’ve received your details!">ได้รับข้อมูลแล้วครับ 💚</h2><p data-en="Buddy will check your size, preferred date and requirements. You can send photos of your items on LINE.">Buddy จะนำขนาด วันที่ต้องการใช้ และรายละเอียดของคุณไปเช็กให้ หากต้องการส่งรูปของเพิ่มเติม สามารถส่งทาง LINE ได้เลย</p><a class="primary" id="successLine" href="https://line.me/R/ti/p/%40storagebuddy" target="_blank" rel="noopener" data-en="Send item photos to Buddy on LINE">ส่งรูปให้ Buddy ทาง LINE</a><a id="successMessenger" class="secondary" href="https://www.facebook.com/profile.php?id=61594516011998" target="_blank" rel="noopener" hidden data-en="Message Buddy on Facebook">ทัก Buddy ทาง Facebook</a><p class="small-note" data-en="No payment or deposit has been collected.">ยังไม่มีการชำระเงินหรือค่ามัดจำในขั้นตอนนี้</p><a href="/" data-en="Back to website">กลับไปดูเว็บไซต์</a></section></main>
<footer class="form-footer"><strong>StorageBuddy Rama 3</strong><div><a href="tel:+66628793645">062-879-3645</a> · <a href="https://line.me/R/ti/p/%40storagebuddy" target="_blank" rel="noopener">LINE @storagebuddy</a></div><p>FLOWCRAFT PROCESS SOLUTION CO.,LTD.</p><button type="button" data-privacy data-en="Privacy policy">ความเป็นส่วนตัว</button></footer>${privacy}
<script>${credentials}\nconst DEMAND_CONFIG=${JSON.stringify(config)};const params=new URLSearchParams(location.search);const source=(params.get('utm_source')||'shared_form').slice(0,120);${persistence}</script><script src="/assets/registration.js?v=demand-v3"></script><script src="/assets/questionnaire-ai.js?v=2"></script></body></html>`.replaceAll('src="assets/','src="/assets/');
}
module.exports={renderRegistrationPage};
