const SITE='https://storagebuddyth.com';
const PHONE='+66-62-879-3645';
const LINE='https://line.me/R/ti/p/%40storagebuddy';
const pairs={
  sizes:['/sizes/','/en/sizes/'],
  location:['/location/rama-3/','/en/location/rama-3/'],
  personal:['/personal-storage/','/en/personal-storage/'],
  business:['/business-storage/','/en/business-storage/']
};
const schema=()=>JSON.stringify({'@context':'https://schema.org','@type':'Organization',name:'StorageBuddy',alternateName:'สตอเรจบัดดี้',url:SITE+'/',logo:SITE+'/assets/storagebuddy_logo_20260912.png',telephone:PHONE,email:'nathaphon.u@flowcraftprocesssolution.com',sameAs:[LINE]});
const nav=(en,alternateUrl)=>`<header class="site-header"><a class="logo" href="${en?'/en/':'/'}"><img src="/assets/storagebuddy_logo_20260912.png" width="1254" height="1254" alt="StorageBuddy สตอเรจบัดดี้"></a><nav aria-label="${en?'Main':'เมนูหลัก'}"><a href="${en?'/en/sizes/':'/sizes/'}">${en?'Size guide':'คู่มือขนาด'}</a><a href="${en?'/en/location/rama-3/':'/location/rama-3/'}">${en?'Rama 3 plan':'แผนพระราม 3'}</a><a href="${en?'/en/personal-storage/':'/personal-storage/'}">${en?'Personal':'ของใช้ส่วนตัว'}</a><a href="${en?'/en/business-storage/':'/business-storage/'}">${en?'Business':'ธุรกิจ'}</a></nav><a class="language" href="${alternateUrl}" hreflang="${en?'th-TH':'en-TH'}">${en?'ไทย':'English'}</a></header>`;
const preserveQueryScript=`<script>function withCurrentQuery(href){const url=new URL(href,location.origin);if(url.origin!==location.origin)return href;return url.pathname+location.search+url.hash}if(location.search)document.querySelectorAll('a[href]').forEach(link=>{const href=link.getAttribute('href');if(!href||href.startsWith('#'))return;const url=new URL(href,location.href);if(url.origin===location.origin)link.setAttribute('href',withCurrentQuery(href))})</script>`;
const footer=(en)=>`<footer><div><strong>StorageBuddy · สตอเรจบัดดี้</strong><p>${en?'Planning self storage near the HomePro Rama 3 area. The facility location, opening and room inventory are not yet confirmed.':'กำลังวางแผนห้องเก็บของใกล้ย่าน HomePro พระราม 3 สถานที่จริง วันเปิด และจำนวนห้องยังไม่ยืนยัน'}</p></div><div><a href="tel:+66628793645">062-879-3645</a> · <a href="${LINE}">LINE @storagebuddy</a></div></footer>`;
const page=({lang,key,title,description,h1,intro,body})=>{
  const en=lang==='en', [thUrl,enUrl]=pairs[key],url=en?enUrl:thUrl;
  return `<!doctype html>
<html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${title}</title><meta name="description" content="${description}"><link rel="canonical" href="${SITE}${url}">
<link rel="alternate" hreflang="th-TH" href="${SITE}${thUrl}"><link rel="alternate" hreflang="en-TH" href="${SITE}${enUrl}"><link rel="alternate" hreflang="x-default" href="${SITE}${thUrl}">
<meta property="og:type" content="website"><meta property="og:site_name" content="StorageBuddy สตอเรจบัดดี้"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:url" content="${SITE}${url}"><meta property="og:image" content="${SITE}/assets/storagebuddy_banner.webp">
<link rel="icon" href="/assets/storagebuddy_logo_20260912.png"><link rel="stylesheet" href="/assets/seo-pages.css"><script type="application/ld+json">${schema()}</script></head><body>
<a class="skip" href="#main">${en?'Skip to content':'ข้ามไปยังเนื้อหา'}</a>${nav(en,en?thUrl:enUrl)}<main id="main"><section class="hero"><p class="eyebrow">STORAGEBUDDY · ${en?'PLANNING RAMA 3':'วางแผนพื้นที่พระราม 3'}</p><h1>${h1}</h1><p class="lead">${intro}</p><div class="notice"><strong>${en?'Pre-opening information':'ข้อมูลก่อนเปิดบริการ'}</strong> ${en?'The customer-facing facility location, opening date and room inventory have not been confirmed. Examples on this page are guidance only.':'สถานที่ให้บริการจริง วันเปิด และจำนวนห้องยังไม่ยืนยัน ตัวอย่างในหน้านี้ใช้เป็นแนวทางเท่านั้น'}</div></section>${body}<section class="cta"><h2>${en?'Tell Buddy what you need':'บอกบัดดี้ว่าคุณต้องการเก็บอะไร'}</h2><p>${en?'Use the size adviser or register your interest to receive confirmed location, opening and quotation details before you decide.':'ใช้ตัวช่วยเลือกขนาด หรือลงทะเบียนความสนใจ เพื่อรับข้อมูลทำเล วันเปิด และใบเสนอราคาที่ได้รับการยืนยันก่อนตัดสินใจ'}</p><div class="actions"><a class="button" href="${en?'/en/':'/'}#size-help">${en?'Use the size adviser':'ใช้ตัวช่วยเลือกขนาด'}</a><a class="button secondary" href="${en?'/en/':'/'}#contact">${en?'Register an enquiry':'ลงทะเบียนสอบถาม'}</a><a class="text" href="${LINE}">${en?'Chat on LINE':'แชท LINE'}</a></div></section></main>${footer(en)}${preserveQueryScript}</body></html>`;
};
const cards=(items)=>`<div class="cards">${items.map(([h,p])=>`<article><h2>${h}</h2><p>${p}</p></article>`).join('')}</div>`;
const pages=[
 {file:'sizes/index.html',html:page({lang:'th',key:'sizes',title:'คู่มือขนาดห้องเก็บของ 1–8 ตร.ม. พระราม 3 | StorageBuddy',description:'เปรียบเทียบห้องเก็บของ 1, 2, 3, 4, 5 และ 8 ตร.ม. สำหรับของใช้ เฟอร์นิเจอร์และสต็อก พร้อมคำแนะนำแบบไม่รับประกันว่าของจะพอดี',h1:'คู่มือเลือกขนาดห้องเก็บของ 1–8 ตร.ม.',intro:'ห้องเก็บของรายเดือน พระราม 3 ที่อยู่ในแผนมีตัวอย่างหลายขนาด เริ่มจากรายการของ เผื่อทางหยิบใช้งาน แล้วให้บัดดี้ช่วยตรวจก่อนรับข้อเสนอที่ยืนยันแล้ว',body:cards([['1 ตร.ม.','แนวทางสำหรับกระเป๋า กล่อง หรืออุปกรณ์ชิ้นเล็ก วัดของชิ้นใหญ่ที่สุดก่อนเลือก'],['2 ตร.ม.','ตัวอย่างสำหรับกล่องเอกสาร หนังสือ กระเป๋า และของตามฤดูกาลที่แพ็กซ้อนได้'],['3 ตร.ม.','แนวทางสำหรับของจากคอนโดหลายชิ้น เช่น กล่อง กระเป๋า และชั้นวางขนาดเล็ก'],['4 ตร.ม.','อาจเหมาะกับจักรยาน อุปกรณ์กีฬา และกล่องหลายใบ เมื่อเผื่อพื้นที่ทางเดินแล้ว'],['5 ตร.ม.','แนวทางสำหรับเฟอร์นิเจอร์ชิ้นเล็กและของระหว่างย้ายบ้านหรือรีโนเวท'],['8 ตร.ม.','ตัวอย่างสำหรับของหลายประเภท เฟอร์นิเจอร์หลายชิ้น หรือสต็อกธุรกิจขนาดย่อม']])+`<p class="caveat">ภาพและรายการทั้งหมดเป็นเพียงตัวอย่าง ไม่รับประกันว่าของจะพอดี รูปร่างห้อง ความสูง ทางเข้า การซ้อน และพื้นที่หยิบของอาจทำให้ขนาดที่ต้องการเปลี่ยนไป</p>`})},
 {file:'en/sizes/index.html',html:page({lang:'en',key:'sizes',title:'Storage Unit Size Guide 1–8 sqm Rama 3 | StorageBuddy',description:'Compare illustrative 1, 2, 3, 4, 5 and 8 sqm storage guidance for belongings, furniture and small business stock near Rama 3.',h1:'Storage unit size guide: 1–8 sqm',intro:'List and measure your items, allow retrieval space, then ask Buddy to review the fit before any confirmed offer.',body:cards([['1 sqm','Guidance for bags, boxes or compact equipment. Measure the largest item first.'],['2 sqm','An example for archive boxes, books, luggage and stackable seasonal belongings.'],['3 sqm','Guidance for mixed condo belongings such as boxes, luggage and compact shelving.'],['4 sqm','May suit a bicycle, sports equipment and several boxes after allowing an access path.'],['5 sqm','Guidance for small furniture and packed belongings during a move or renovation.'],['8 sqm','An example for mixed belongings, several furniture pieces or small business stock.']])+`<p class="caveat">All layouts and item lists are illustrative, not a fit guarantee. Room shape, height, doorway, stacking and retrieval space can change the area required.</p>`})},
 {file:'location/rama-3/index.html',html:page({lang:'th',key:'location',title:'ห้องเก็บของให้เช่า พระราม 3 ใกล้ HomePro (แผน) | StorageBuddy',description:'ข้อมูลแผนห้องเก็บของย่านพระราม 3 ใกล้ HomePro เชื่อมสาธุประดิษฐ์ ยานนาวา บางคอแหลมและสาทร โดยทำเลจริงและวันเปิดยังไม่ยืนยัน',h1:'แผนห้องเก็บของให้เช่าใกล้ HomePro พระราม 3',intro:'หากคุณกำลังพิจารณาเช่าที่เก็บของ พระราม 3 สตอเรจบัดดี้กำลังศึกษาพื้นที่ในย่าน HomePro พระราม 3 สำหรับความต้องการจากบ้าน คอนโด และธุรกิจใกล้เคียง',body:`<section><h2>พื้นที่ที่เรากำลังศึกษา</h2><p>ย่านพระราม 3 เชื่อมต่อสาธุประดิษฐ์ ยานนาวา บางคอแหลม และสาทร จึงเป็นจุดที่ผู้พักอาศัยและธุรกิจอาจมองหาพื้นที่เพิ่ม เราใช้ชื่อย่านเหล่านี้เพื่ออธิบายพื้นที่รับความสนใจ ไม่ได้หมายความว่ามีสาขาหรือห้องพร้อมใช้ในแต่ละย่าน</p><h2>สถานะทำเล</h2><p>HomePro พระราม 3 เป็นเพียงจุดอ้างอิงของย่าน ไม่ใช่ที่อยู่สถานที่เก็บของ ที่อยู่จดทะเบียนบริษัทไม่ใช่สถานที่ให้บริการ เราจะแจ้งตำแหน่งจริงและวันเปิดเมื่อยืนยันแล้ว</p></section>`})},
 {file:'en/location/rama-3/index.html',html:page({lang:'en',key:'location',title:'Planned Self Storage near HomePro Rama 3 | StorageBuddy',description:'Planned self storage around the HomePro Rama 3 area for Rama 3, Sathu Pradit, Yan Nawa, Bang Kho Laem and Sathorn. Site and opening unconfirmed.',h1:'Planned self storage near HomePro Rama 3',intro:'StorageBuddy is studying the HomePro Rama 3 area for personal and business storage demand.',body:`<section><h2>The area we are studying</h2><p>Rama 3 connects with Sathu Pradit, Yan Nawa, Bang Kho Laem and Sathorn. These catchment names describe where enquiries may come from; they do not mean a branch or rooms exist in each district.</p><h2>Location status</h2><p>HomePro Rama 3 is an area reference, not the storage address. The registered company address is not the facility. We will share the customer-facing location and opening details only after confirmation.</p></section>`})},
 {file:'personal-storage/index.html',html:page({lang:'th',key:'personal',title:'ห้องเก็บของสำหรับคอนโด ย้ายบ้านและรีโนเวท | StorageBuddy',description:'แนวทางเลือกพื้นที่เก็บของใช้ส่วนตัว ของจากคอนโด เฟอร์นิเจอร์ ระหว่างย้ายบ้านหรือรีโนเวท พร้อมตัวช่วยประเมินขนาด',h1:'พื้นที่เก็บของใช้ส่วนตัว เมื่อบ้านต้องการพื้นที่หายใจ',intro:'วางแผนแยกของที่ต้องใช้ ของที่เก็บชั่วคราว และของชิ้นใหญ่ เพื่อเลือกขนาดโดยไม่เช่าพื้นที่เกินจำเป็น',body:cards([['ของจากคอนโด','รวมกล่อง กระเป๋า ของตามฤดูกาล และอุปกรณ์งานอดิเรก พร้อมจดขนาดของชิ้นใหญ่'],['ย้ายบ้าน','แบ่งของตามวันที่ต้องใช้และติดฉลาก เพื่อหยิบของจำเป็นได้โดยไม่รื้อทุกกล่อง'],['รีโนเวท','วัดเฟอร์นิเจอร์และทางขนย้าย รวมพื้นที่กันกระแทกก่อนประเมินขนาด'],['เก็บเฟอร์นิเจอร์','ถอดชิ้นส่วนได้เมื่อเหมาะสม เก็บอุปกรณ์ยึดไว้ด้วยกัน และระบุของที่ห้ามวางซ้อน']])})},
 {file:'en/personal-storage/index.html',html:page({lang:'en',key:'personal',title:'Personal Storage for Condos, Moving & Renovation | StorageBuddy',description:'Plan storage for condo belongings, moving, renovation and furniture with an illustrative size guide and personal advice from StorageBuddy.',h1:'Personal storage when home needs breathing room',intro:'Separate everyday items, temporary storage and bulky furniture so you can estimate space without overcommitting.',body:cards([['Condo belongings','List boxes, luggage, seasonal belongings and hobby equipment, including the largest measurements.'],['Moving home','Group items by the date you need them and label boxes so essentials remain easy to retrieve.'],['Renovation','Measure furniture and the moving route, then allow protection and handling space.'],['Furniture storage','Dismantle suitable pieces, keep fixings together and flag anything that cannot be stacked.']])})},
 {file:'business-storage/index.html',html:page({lang:'th',key:'business',title:'ห้องเก็บสต็อกสินค้าและเอกสารสำหรับธุรกิจ | StorageBuddy',description:'แนวทางพื้นที่เก็บสต็อกสินค้า เอกสารและอุปกรณ์สำหรับธุรกิจขนาดเล็ก พร้อมอธิบายความต่างจากโกดังโลจิสติกส์เต็มรูปแบบ',h1:'พื้นที่เก็บของสำหรับธุรกิจที่ต้องการความยืดหยุ่น',intro:'ผู้ที่กำลังเปรียบเทียบโกดังขนาดเล็กให้เช่า ควรเริ่มจากปริมาตร การหมุนเวียน และทางหยิบของ แผนของเรามุ่งเป็นพื้นที่เสริมสำหรับสต็อก เอกสาร หรืออุปกรณ์ ไม่ใช่คลังโลจิสติกส์เต็มรูปแบบ',body:cards([['สต็อกสินค้า','นับจำนวนลัง ขนาด และรอบเติมสินค้า เผื่อช่องทางเข้าถึงสินค้าที่หมุนเร็ว'],['เอกสารบริษัท','จัดตามช่วงเวลาที่ต้องเก็บ ติดป้าย และวางแผนชั้นโดยคำนึงถึงน้ำหนัก'],['อุปกรณ์ธุรกิจ','แยกของเปราะบาง ของหนัก และของที่ต้องหยิบบ่อยก่อนประเมินพื้นที่'],['ไม่ใช่โกดังโลจิสติกส์','ห้องเก็บของขนาดย่อมไม่ใช่โกดังโลจิสติกส์เต็มรูปแบบ เราไม่ได้อ้างบริการรับสินค้า แพ็ก จัดส่ง หรือบริหารคลัง']])})},
 {file:'en/business-storage/index.html',html:page({lang:'en',key:'business',title:'Small Business Inventory & Document Storage | StorageBuddy',description:'Guidance for small business inventory, documents and equipment storage, clearly distinguished from a full logistics warehouse.',h1:'Flexible storage planning for small businesses',intro:'Estimate extra space for inventory, documents or equipment by considering volume, turnover and retrieval paths.',body:cards([['Inventory','Count cartons, dimensions and replenishment cycles, leaving access to faster-moving stock.'],['Documents','Group records by retention period, label clearly and plan shelving around weight.'],['Business equipment','Separate fragile, heavy and frequently retrieved items before estimating space.'],['Not a full logistics warehouse','A compact storage room is not a full logistics warehouse. We do not claim receiving, packing, shipping or warehouse-management services.']])})}
];
module.exports={pages};
