// Regression for the main site -> separate demand questionnaire transition.
const assert=require('node:assert/strict');const {launchBrowser,outputPath}=require('./browser-runtime.cjs');
(async()=>{const browser=await launchBrowser();try{const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*.supabase.co/rest/v1/**',r=>r.fulfill({status:201,body:'[]'}));
 await page.goto('http://127.0.0.1:8788/?utm_source=setup_test_demand&utm_campaign=main',{waitUntil:'networkidle'});
 for(const language of ['th','en']){if(language==='en'){await page.locator('#langBtn').click();await page.waitForURL('**/en/**');}for(const width of [390,768,1440]){await page.setViewportSize({width,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow '+language+width);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:outputPath('demand-home-'+language+'-'+width+'.png')});}}
 assert(!(await page.locator('body').innerText()).includes('50%'));await page.locator('.demand-hero-actions a').first().click();await page.waitForURL('**/register/**');assert.equal(new URL(page.url()).searchParams.get('lang'),'en');assert.equal(new URL(page.url()).searchParams.get('utm_campaign'),'main');assert(await page.locator('#demandForm').isVisible());
 await page.goto('http://127.0.0.1:8788/?utm_source=setup_test_demand');await page.locator('#sizeGrid button').filter({hasText:'4 '}).click();await page.locator('#sizeCta').click();await page.waitForURL('**/register/**');assert(await page.locator('[name="requested_size"][value="3_4"]').isChecked());assert.equal(new URL(page.url()).searchParams.get('size'),'4');
 await page.goto('http://127.0.0.1:8788/');await page.route('**/api/estimate',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({min_sqm:2,max_sqm:3,items:['10 boxes'],questions:[],confidence:'medium',reasoning:'Allow access.'})}));await page.locator('#itemDescription').fill('10 boxes for moving');await page.locator('#estimateBtn').click();await page.locator('#aiResult').waitFor({state:'visible'});await page.locator('#aiResult button').click();await page.locator('#sizeCta').click();await page.waitForURL('**/register/**');assert.equal(await page.locator('#itemDescription').inputValue(),'10 boxes for moving');assert(await page.locator('[name="requested_size"][value="3_4"]').isChecked());assert.equal(await page.evaluate(()=>context.ai_estimate.min_sqm),2);assert.equal(await page.evaluate(()=>sessionStorage.getItem('sb_intake_context')),null);
 assert.deepEqual(errors,[]);console.log('PASS bilingual main-site layout, honest copy, CTA to separate form, campaign retention, selected size and AI context transfer');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
