const assert=require('node:assert/strict');const {launchBrowser,outputPath}=require('./browser-runtime.cjs');
(async()=>{const browser=await launchBrowser();try{
 const page=await browser.newPage(),saved=[],errors=[];let fail=true;page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*.supabase.co/rest/v1/**',r=>{if(r.request().url().includes('/leads')){if(fail)return r.fulfill({status:500,body:'{}'});saved.push(r.request().postDataJSON());}return r.fulfill({status:201,body:'[]'});});
 await page.goto('http://127.0.0.1:8788/register/?utm_source=facebook&utm_medium=paid_social&utm_campaign=first-customers&utm_content=ad-A',{waitUntil:'networkidle'});
 assert(await page.locator('#demandForm').isVisible());assert.equal(await page.locator('#size-help').count(),0);assert(!(await page.locator('#phone').isVisible()));
 for(const width of [390,1440]){await page.setViewportSize({width,height:950});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:outputPath('demand-step1-'+width+'.png'),fullPage:true});}
 await page.locator('#nextBtn').click();assert(await page.locator('[data-step="0"]').isVisible());
 await page.locator('[name="use_case"][value="moving"]').check();await page.locator('[name="use_case"][value="furniture"]').check();await page.locator('[name="requested_size"][value="3_4"]').check();await page.locator('#itemDescription').fill('10 boxes and a sofa');await page.locator('#nextBtn').click();
 assert(await page.locator('#targetQuote').isHidden());assert(await page.locator('#budgetOnly').isVisible());await page.setViewportSize({width:390,height:950});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:outputPath('demand-step2-390.png'),fullPage:true});
 await page.locator('[name="desired_move_in"][value="within_7_days"]').check();await page.locator('[name="expected_duration"][value="3_6_months"]').check();await page.locator('#budget').fill('3500');await page.locator('#nextBtn').click();
 await page.locator('[name="readiness_level"][value="ready_to_confirm"]').check();await page.locator('[name="contact_preference"][value="line"]').check();await page.locator('#lineId').fill('test-line');await page.locator('#customerName').fill('TEST ONLY DEMAND');await page.locator('#phone').fill('0000000000');await page.locator('#consent').check();
 await page.screenshot({path:outputPath('demand-step3-390.png'),fullPage:true});await page.locator('#langBtn').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await page.locator('#customerName').inputValue(),'TEST ONLY DEMAND');assert.equal(await page.locator('html').getAttribute('lang'),'en');
 await page.locator('#backBtn').click();assert.equal(await page.locator('#budget').inputValue(),'3500');await page.locator('#nextBtn').click();
 await page.locator('#submitBtn').click();await page.waitForFunction(()=>document.getElementById('formMessage').textContent.includes('couldn'));assert(await page.locator('#demandForm').isVisible());assert.equal(await page.locator('#phone').inputValue(),'0000000000');
 fail=false;await page.locator('#submitBtn').click();await page.locator('#leadSuccess').waitFor({state:'visible'});assert.equal(saved.length,1);const row=saved[0],d=JSON.parse(row.customer_use);
 assert.equal(row.utm_source,'facebook');assert.deepEqual(d.storage_use_case,['moving','furniture']);assert.equal(d.requested_size,'3_4');assert.equal(d.quoted_price,null);assert.equal(d.price_response,null);assert.equal(d.budget_thb,3500);assert.equal(d.readiness_level,'ready_to_confirm');assert.equal(d.desired_move_in,'within_7_days');assert.equal(d.expected_duration,'3_6_months');assert.equal(d.line_id,'test-line');assert.equal(d.contact_preference,'line');assert.equal(d.campaign,'first-customers');assert.equal(d.ad,'ad-A');assert.equal(d.medium,'paid_social');assert.equal(d.email,'');assert.equal(d.lead_status,'NEW');assert.equal(d.payment_status,'not_collected');
 await page.screenshot({path:outputPath('demand-success.png')});assert(await page.locator('#successLine').isVisible());assert.deepEqual(errors,[]);
 console.log('PASS V2 questionnaire: mobile/desktop, validation, three steps, no unapproved price, contact last, language/back retain answers, failed save/retry, exact intent payload and LINE success');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
